lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'  # Chemin de la clé privée
    public_key: '%kernel.project_dir%/config/jwt/public.pem' 
    pass_phrase: 'azerty'
    token_ttl: 3600
