vich_uploader:
    db_driver: orm
    mappings:
        user_image:
            uri_prefix: '%app.path.user_images%'
            upload_destination: '%kernel.project_dir%/public/uploads/users'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        film_image:
            uri_prefix: '%app.path.film_images%'
            upload_destination: '%kernel.project_dir%/public/uploads/films'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            
